#!/bin/sh

xrdbquery() {
    xrdb -query | grep "$@" | awk 'NR==1{print $2}'
}

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d          
#               1 2 3 4 5 6 7 8 9 10

bspc rule -a firefox   desktop=^1     follow=off -o
bspc rule -a obsidian  desktop=^2     follow=off -o
bspc rule -a Alacritty desktop=^3     follow=off -o
bspc rule -a selwindow state=floating center=on focus=on rectangle=600x470+0+0

bspc config normal_border_color  "$(xrdbquery background)"
bspc config active_border_color  "$(xrdbquery color4)"
bspc config focused_border_color "$(xrdbquery color4)"

bspc config border_width         3
bspc config window_gap           9

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

"$HOME/.config/polybar/launch.sh"
